
imagePullSecrets: []

yurtControllerManager:
  replicaCount: 1
  tolerations: []
  image:
    registry: docker.io
    repository: openyurt/yurt-controller-manager
    pullPolicy: IfNotPresent
    tag: v1.1.0
  service:
    type: ClusterIP
    port: 80

admissionWebhooks:
  service:
    type: ClusterIP
    port: 9443
  failurePolicy: Fail
  certificate:
    mountPath: /tmp/k8s-webhook-server/serving-certs
  names:
    validatingWebhookName: vpoolcoordinator.openyurt.io
    mutatingWebhookName: mpoolcoordinator.openyurt.io
    webhookPodValidatingPath: /pool-coordinator-webhook-validate
    webhookPodMutatingPath: /pool-coordinator-webhook-mutate

yurtTunnelAgent:
  replicaCount: 1
  tolerations: []
  parameters:
    tunnelserverAddr: ""
  image:
    registry: docker.io
    repository: openyurt/yurt-tunnel-agent
    pullPolicy: IfNotPresent
    tag: v1.1.0

yurtTunnelServer:
  replicaCount: 1
  tolerations: []
  parameters:
    certDnsNames: ""
    certIps: ""
    tunnelAgentConnectPort: 10262
  image:
    registry: docker.io
    repository: openyurt/yurt-tunnel-server
    pullPolicy: IfNotPresent
    tag: v1.1.0

yurtHub:
  cacheAgents: ""
